import { AutoroutingPipelineDebugger } from "lib/testing/AutoroutingPipelineDebugger"
import { SimpleRouteJson } from "lib/types"

export const simpleRouteJson: SimpleRouteJson = {
  bounds: {
    minX: -5,
    maxX: 5,
    minY: -5,
    maxY: 5,
  },
  obstacles: [
    {
      type: "rect",
      layers: ["top"],
      center: {
        x: 2.5,
        y: 0,
      },
      width: 0.6,
      height: 0.6,
      connectedTo: [
        "pcb_smtpad_0",
        "connectivity_net7",
        "source_trace_3",
        "source_port_3",
        "source_trace_2",
        "source_port_2",
        "source_trace_1",
        "source_port_1",
        "source_trace_0",
        "source_port_0",
        "source_net_0",
        "pcb_smtpad_0",
        "pcb_port_0",
        "pcb_smtpad_1",
        "pcb_port_1",
        "pcb_smtpad_2",
        "pcb_port_2",
        "pcb_smtpad_3",
        "pcb_port_3",
      ],
    },
    {
      type: "rect",
      layers: ["top"],
      center: {
        x: 3.5,
        y: 0,
      },
      width: 0.6,
      height: 0.6,
      connectedTo: [
        "pcb_smtpad_1",
        "connectivity_net7",
        "source_trace_3",
        "source_port_3",
        "source_trace_2",
        "source_port_2",
        "source_trace_1",
        "source_port_1",
        "source_trace_0",
        "source_port_0",
        "source_net_0",
        "pcb_smtpad_0",
        "pcb_port_0",
        "pcb_smtpad_1",
        "pcb_port_1",
        "pcb_smtpad_2",
        "pcb_port_2",
        "pcb_smtpad_3",
        "pcb_port_3",
      ],
    },
    {
      type: "rect",
      layers: ["top"],
      center: {
        x: -3.5,
        y: 0,
      },
      width: 0.6,
      height: 0.6,
      connectedTo: [
        "pcb_smtpad_2",
        "connectivity_net7",
        "source_trace_3",
        "source_port_3",
        "source_trace_2",
        "source_port_2",
        "source_trace_1",
        "source_port_1",
        "source_trace_0",
        "source_port_0",
        "source_net_0",
        "pcb_smtpad_0",
        "pcb_port_0",
        "pcb_smtpad_1",
        "pcb_port_1",
        "pcb_smtpad_2",
        "pcb_port_2",
        "pcb_smtpad_3",
        "pcb_port_3",
      ],
    },
    {
      type: "rect",
      layers: ["top"],
      center: {
        x: -2.5,
        y: 0,
      },
      width: 0.6,
      height: 0.6,
      connectedTo: [
        "pcb_smtpad_3",
        "connectivity_net7",
        "source_trace_3",
        "source_port_3",
        "source_trace_2",
        "source_port_2",
        "source_trace_1",
        "source_port_1",
        "source_trace_0",
        "source_port_0",
        "source_net_0",
        "pcb_smtpad_0",
        "pcb_port_0",
        "pcb_smtpad_1",
        "pcb_port_1",
        "pcb_smtpad_2",
        "pcb_port_2",
        "pcb_smtpad_3",
        "pcb_port_3",
      ],
    },
  ],
  connections: [
    {
      name: "source_net_0",
      pointsToConnect: [
        {
          pointId: "TEST_POINT_0",
          x: 2.5,
          y: 0,
          layer: "top",
          pcb_port_id: "pcb_port_0",
        },
        {
          x: 3.5,
          y: 0,
          layer: "top",
          pcb_port_id: "pcb_port_1",
        },
        {
          x: -3.5,
          y: 0,
          layer: "top",
          pcb_port_id: "pcb_port_2",
        },
        {
          pointId: "TEST_POINT_1",
          x: -2.5,
          y: 0,
          layer: "top",
          pcb_port_id: "pcb_port_3",
        },
      ],
      externallyConnectedPointIds: [["TEST_POINT_0", "TEST_POINT_1"]],
    },
  ],
  layerCount: 2,
  minTraceWidth: 0.15,
}

export default () => <AutoroutingPipelineDebugger srj={simpleRouteJson} />
