import { expect, test, describe } from "bun:test"
import { CapacityMeshSolver } from "../lib"
import { SimpleRouteJson } from "lib/types"

describe("CapacityMeshSolver", () => {
  test("getOutputSimpleRouteJson throws when solver is not complete", () => {
    const simpleSrj = {
      layerCount: 2,
      minTraceWidth: 0.15,
      obstacles: [],
      connections: [],
      bounds: { minX: 0, maxX: 100, minY: 0, maxY: 100 },
    }

    const solver = new CapacityMeshSolver(simpleSrj)

    expect(() => solver.getOutputSimpleRouteJson()).toThrow(
      "Cannot get output before solving is complete",
    )
  })

  test("should solve with obstacles and connections", async () => {
    const simpleSrj: SimpleRouteJson = {
      layerCount: 2,
      minTraceWidth: 0.15,
      obstacles: [
        {
          type: "rect",
          layers: ["top", "bottom"],
          center: { x: 50, y: 50 },
          width: 20,
          height: 20,
          connectedTo: [],
        },
      ],
      connections: [
        {
          name: "connection1",
          pointsToConnect: [
            { x: 10, y: 10, layer: "top", pcb_port_id: "port1" },
            { x: 90, y: 90, layer: "top", pcb_port_id: "port2" },
          ],
        },
        {
          name: "connection2",
          pointsToConnect: [
            { x: 10, y: 90, layer: "top", pcb_port_id: "port3" },
            { x: 90, y: 10, layer: "top", pcb_port_id: "port4" },
            { x: 40, y: 10, layer: "top", pcb_port_id: "port4" },
          ],
        },
      ],
      bounds: { minX: 0, maxX: 100, minY: 0, maxY: 100 },
    }

    const solver = new CapacityMeshSolver(simpleSrj)
    await solver.solve()

    const result = solver.getOutputSimpleRouteJson()
    expect(result.traces).toMatchInlineSnapshot(`
      [
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst0",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.84375,
              "y": 9.9609375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 90.0390625,
              "y": 9.9609375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 90.0390625,
              "y": 9.9609375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.84375,
              "y": 9.9609375,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst0",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.453125,
              "y": 9.375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.453125,
              "y": 9.765625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.453125,
              "y": 9.765625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.84375,
              "y": 9.9609375,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst0",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 87.5,
              "y": 7.8125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.0625,
              "y": 7.8125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.0625,
              "y": 7.8125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.453125,
              "y": 9.375,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst0",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 75,
              "y": 6.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 81.25,
              "y": 6.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 81.25,
              "y": 6.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 87.5,
              "y": 7.8125,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst0",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 50,
              "y": 18.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 62.5,
              "y": 12.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 62.5,
              "y": 12.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 75,
              "y": 6.25,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst0",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 42.1875,
              "y": 12.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 43.75,
              "y": 18.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 43.75,
              "y": 18.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 50,
              "y": 18.75,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst0",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 40.625,
              "y": 10.546875,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 42.1875,
              "y": 10.9375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 42.1875,
              "y": 10.9375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 42.1875,
              "y": 12.5,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst0",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 40.0390625,
              "y": 10.15625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 40.234375,
              "y": 10.546875,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 40.234375,
              "y": 10.546875,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 40.625,
              "y": 10.546875,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst0",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 40.0390625,
              "y": 10.15625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 40.0390625,
              "y": 10.15625,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 39.84375,
              "y": 9.9609375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 39.84375,
              "y": 9.9609375,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 39.453125,
              "y": 9.375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 39.453125,
              "y": 9.765625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 39.453125,
              "y": 9.765625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 39.84375,
              "y": 9.9609375,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 37.5,
              "y": 7.8125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 39.0625,
              "y": 7.8125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 39.0625,
              "y": 7.8125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 39.453125,
              "y": 9.375,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 12.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 6.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 6.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 37.5,
              "y": 7.8125,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 18.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 18.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 12.5,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 25,
              "y": 31.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 31.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 31.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 25,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 7.8125,
              "y": 87.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 6.25,
              "y": 81.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 6.25,
              "y": 81.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 6.25,
              "y": 75,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.375,
              "y": 89.453125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 7.8125,
              "y": 89.0625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 7.8125,
              "y": 89.0625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 7.8125,
              "y": 87.5,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.9609375,
              "y": 89.84375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.765625,
              "y": 89.453125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.765625,
              "y": 89.453125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.375,
              "y": 89.453125,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.9609375,
              "y": 89.84375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.9609375,
              "y": 90.0390625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.9609375,
              "y": 90.0390625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.9609375,
              "y": 89.84375,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.84375,
              "y": 90.0390625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 90.0390625,
              "y": 90.0390625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 90.0390625,
              "y": 90.0390625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.84375,
              "y": 90.0390625,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.453125,
              "y": 90.625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.453125,
              "y": 90.234375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.453125,
              "y": 90.234375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.84375,
              "y": 90.0390625,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 87.5,
              "y": 92.1875,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.0625,
              "y": 92.1875,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.0625,
              "y": 92.1875,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 89.453125,
              "y": 90.625,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 75,
              "y": 93.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 81.25,
              "y": 93.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 81.25,
              "y": 93.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 87.5,
              "y": 92.1875,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 50,
              "y": 87.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 62.5,
              "y": 87.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 62.5,
              "y": 87.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 75,
              "y": 93.75,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 37.5,
              "y": 87.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 37.5,
              "y": 87.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 50,
              "y": 87.5,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 6.25,
              "y": 75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 15.849999999999998,
              "y": 65.39999999999999,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 15.849999999999998,
              "y": 52.59999999999998,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 16.666666666666664,
              "y": 50,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 25,
              "y": 68.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.6,
              "y": 62.349999999999994,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.6,
              "y": 59.14999999999999,
            },
            {
              "from_layer": "top",
              "route_type": "via",
              "to_layer": "bottom",
              "x": 18.6,
              "y": 59.14999999999999,
            },
            {
              "layer": "bottom",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.6,
              "y": 59.14999999999999,
            },
            {
              "layer": "bottom",
              "route_type": "wire",
              "width": 0.15,
              "x": 15.400000000000002,
              "y": 55.94999999999999,
            },
            {
              "layer": "bottom",
              "route_type": "wire",
              "width": 0.15,
              "x": 15.400000000000002,
              "y": 52.749999999999986,
            },
            {
              "layer": "bottom",
              "route_type": "wire",
              "width": 0.15,
              "x": 12.200000000000003,
              "y": 50,
            },
            {
              "layer": "bottom",
              "route_type": "wire",
              "width": 0.15,
              "x": 12.200000000000003,
              "y": 53.2,
            },
            {
              "from_layer": "bottom",
              "route_type": "via",
              "to_layer": "top",
              "x": 12.200000000000003,
              "y": 53.2,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 12.200000000000003,
              "y": 53.2,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.000000000000004,
              "y": 50,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 8.333333333333332,
              "y": 50,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 25,
              "y": 68.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 68.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 68.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 31.25,
              "y": 75,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection2",
          "pcb_trace_id": "connection2_mst1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 25,
              "y": 31.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 15.400000000000002,
              "y": 40.85000000000001,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 15.400000000000002,
              "y": 47.250000000000014,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 16.666666666666664,
              "y": 50,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.75,
              "y": 25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.150000000000002,
              "y": 34.6,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.150000000000002,
              "y": 47.40000000000001,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 8.333333333333332,
              "y": 50,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.75,
              "y": 12.5,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.75,
              "y": 18.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.75,
              "y": 18.75,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.75,
              "y": 25,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 12.5,
              "y": 7.8125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.75,
              "y": 6.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.75,
              "y": 6.25,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 18.75,
              "y": 12.5,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 10.546875,
              "y": 9.375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 10.9375,
              "y": 7.8125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 10.9375,
              "y": 7.8125,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 12.5,
              "y": 7.8125,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 10.15625,
              "y": 9.9609375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 10.546875,
              "y": 9.765625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 10.546875,
              "y": 9.765625,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 10.546875,
              "y": 9.375,
            },
          ],
          "type": "pcb_trace",
        },
        {
          "connection_name": "connection1",
          "pcb_trace_id": "connection1",
          "route": [
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 10.15625,
              "y": 9.9609375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.9609375,
              "y": 9.9609375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 9.9609375,
              "y": 9.9609375,
            },
            {
              "layer": "top",
              "route_type": "wire",
              "width": 0.15,
              "x": 10.15625,
              "y": 9.9609375,
            },
          ],
          "type": "pcb_trace",
        },
      ]
    `)
  })
})
