export interface HighDensityHyperParameters {
  FUTURE_CONNECTION_PROX_TRACE_PENALTY_FACTOR: number
  FUTURE_CONNECTION_PROX_VIA_PENALTY_FACTOR: number
  FUTURE_CONNECTION_PROXIMITY_VD: number
  MISALIGNED_DIST_PENALTY_FACTOR: number
  VIA_PENALTY_FACTOR_2: number
  SHUFFLE_SEED: number
  CELL_SIZE_FACTOR: number
  FLIP_TRACE_ALIGNMENT_DIRECTION: boolean
}
